# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-25 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180923_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coffee_friends',
            field=models.ManyToManyField(related_name='_user_coffee_friends_+', to='first_app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='lunch_friends',
            field=models.ManyToManyField(related_name='_user_lunch_friends_+', to='first_app.User'),
        ),
    ]
